# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irirCOajjZVKtCMThXbWhFJOaCht296A

#            ***Problem Statement***
### ***Application 3:***
Create a topology of two nodes N0 and N1 connected by a link of bandwidth 1 Mbps and link delay 10 ms. Use a
drop-tail queue at the link. Set the queue size according to bandwidth-delay product. Create a TCP agent (type
of the agent specified below) and FTP traffic at N0 destined for N1. Create 5 CBR traffic agents of rate 300 Kbps
each at N0 destined for N1. Make appropriate assumptions wherever necessary. The timing of the flows are as
follows:
1. FTP starts at 0 sec and continues till the end of simulation.
2. CBR1 starts at 200 ms and continues till end.
3. CBR2 starts at 400 ms and continues till end.
4. CBR3 starts at 600 ms and stops at 1200 ms.
5. CBR4 starts at 800 ms and stops at 1400 ms.
6. CBR5 starts at 1000 ms and stops at 1600 ms.
7. Simulation runs for 1800 ms.
"""

# import libraries needed

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""**Plot graph(s) of TCP congestion window w.r.t. time for following 5 TCP congestion control algorithm
implementations, and describe the TCP congestion control algorithms’ behaviour.**

1.   use TCP New Reno
2.   use TCP Hybla
3.   use TCP Westwood
4.   use TCP Scalable
5.   use TCP Vegas
"""

# Upload Data

import io
from google.colab import files
uploaded=files.upload()

# Plot all the curves together

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (15,10)

data = pd.read_csv("output_cwnd.csv")
xaxes = data['Time']
TcpNewReno = data['TcpNewReno']
TcpHybla = data['TcpHybla']
TcpWestwood = data['TcpWestwood']
TcpVegas = data['TcpVegas']
TcpScalable =  data['TcpScalable']

plt.plot(xaxes,TcpNewReno,color='red',label='TcpNewReno')
plt.plot(xaxes,TcpHybla,color='yellow',label='TcpHybla')
plt.plot(xaxes,TcpWestwood,color='green',label='TcpWestwood')
plt.plot(xaxes,TcpScalable,color='orange',label='TcpScalable')
plt.plot(xaxes,TcpVegas,color='blue',label='TcpVegas')

plt.xlabel('Time(seconds)')
plt.ylabel('TCP Congestion Window Size(Bytes)')
plt.legend()
plt.title('Comparison of TCP Congestion Window Size(Bytes) wrt Time(Seconds)')
plt.grid()
plt.show()

# Plot all the curves independently

fig = plt.figure(figsize=[20,20])
plt1 = fig.add_subplot(321)
plt2 = fig.add_subplot(322)
plt3 = fig.add_subplot(323)
plt4 = fig.add_subplot(324)
plt5 = fig.add_subplot(325)

plt1.plot(xaxes,TcpNewReno,color='red')
plt2.plot(xaxes,TcpHybla,color='yellow')
plt3.plot(xaxes,TcpWestwood,color='green')
plt4.plot(xaxes,TcpScalable,color='orange')
plt5.plot(xaxes,TcpVegas,color='blue')

plt1.set_title('TcpNewReno')
plt2.set_title('TcpHybla')
plt3.set_title('TcpWestwood')
plt4.set_title('TcpScalable')
plt5.set_title('TcpVegas')

plt1.grid()
plt2.grid()
plt3.grid()
plt4.grid()
plt5.grid()

fig.subplots_adjust(hspace=.5,wspace=0.5) 
fig.show()

"""**Draw a graph showing cumulative TCP packets dropped w.r.t. time comparing above 5 TCP congestion
control algorithm implementations.**
"""

# Upload Data

import io
from google.colab import files
uploaded=files.upload()

# Plot all the curves together

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (15,10)

data = pd.read_csv('output_packet_drop.csv')
xaxes = data['Time']
TcpNewReno = data['TcpNewReno']
TcpHybla = data['TcpHybla']
TcpWestwood = data['TcpWestwood']
TcpVegas = data['TcpVegas']
TcpScalable =  data['TcpScalable']


plt.plot(xaxes,TcpNewReno,color='red',label='TcpNewReno')
plt.plot(xaxes,TcpHybla,color='yellow',label='TcpHybla')
plt.plot(xaxes,TcpWestwood,color='green',label='TcpWestwood')
plt.plot(xaxes,TcpScalable,color='orange',label='TcpScalable')
plt.plot(xaxes,TcpVegas,color='blue',label='TcpVegas')


plt.xlabel('Time(seconds)')
plt.ylabel('Cumulative TCP packets dropped')
plt.legend()
plt.title('Comparison of Cumulative TCP packets dropped wrt Time')
plt.grid()
plt.show()

# Plot all the curves independently

fig = plt.figure(figsize=[20,20])
plt1 = fig.add_subplot(321)
plt2 = fig.add_subplot(322)
plt3 = fig.add_subplot(323)
plt4 = fig.add_subplot(324)
plt5 = fig.add_subplot(325)

plt1.plot(xaxes,TcpNewReno,color='red')
plt2.plot(xaxes,TcpHybla,color='yellow')
plt3.plot(xaxes,TcpWestwood,color='green')
plt4.plot(xaxes,TcpScalable,color='orange')
plt5.plot(xaxes,TcpVegas,color='blue')

plt1.set_title('TcpNewReno')
plt2.set_title('TcpHybla')
plt3.set_title('TcpWestwood')
plt4.set_title('TcpScalable')
plt5.set_title('TcpVegas')

plt1.grid()
plt2.grid()
plt3.grid()
plt4.grid()
plt5.grid()

fig.subplots_adjust(hspace=.5,wspace=0.5)
fig.show()

"""**Draw a graph showing cumulative bytes transferred w.r.t. time comparing above 5 TCP congestion
control algorithm implementations.**
"""

# Upload Data

import io
from google.colab import files
uploaded=files.upload()

# Plot all the curves together

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (15,10)

data = pd.read_csv("output_bytes_tx.csv")
xaxes = data['Time']
TcpNewReno = data['TcpNewReno']
TcpHybla = data['TcpHybla']
TcpWestwood = data['TcpWestwood']
TcpVegas = data['TcpVegas']
TcpScalable =  data['TcpScalable']

plt.plot(xaxes,TcpNewReno,color='red',label='TcpNewReno')
plt.plot(xaxes,TcpHybla,color='yellow',label='TcpHybla')
plt.plot(xaxes,TcpWestwood,color='green',label='TcpWestwood')
plt.plot(xaxes,TcpScalable,color='orange',label='TcpScalable')
plt.plot(xaxes,TcpVegas,color='blue',label='TcpVegas')


plt.xlabel('Time(seconds)')
plt.ylabel('TCP Cumulative Bytes Transfered')
plt.legend()
plt.title('Comparison of Cumulative Bytes Transfered wrt Time')
plt.grid()
plt.show()

# Plot all the curves independently

fig = plt.figure(figsize=[20,20])
plt1 = fig.add_subplot(321)
plt2 = fig.add_subplot(322)
plt3 = fig.add_subplot(323)
plt4 = fig.add_subplot(324)
plt5 = fig.add_subplot(325)

plt1.plot(xaxes,TcpNewReno,color='red')
plt2.plot(xaxes,TcpHybla,color='yellow')
plt3.plot(xaxes,TcpWestwood,color='green')
plt4.plot(xaxes,TcpScalable,color='orange')
plt5.plot(xaxes,TcpVegas,color='blue')

plt1.set_title('TcpNewReno')
plt1.set_xlabel('Time(Seconds)')
plt1.set_ylabel('TCP Cumulative byte Transfered')
plt2.set_title('TcpHybla')
plt2.set_xlabel('Time(Seconds)')
plt2.set_ylabel('Cumulative byte Transfered')
plt3.set_title('TcpWestwood')
plt3.set_xlabel('Time(Seconds)')
plt3.set_ylabel('Cumulative byte Transfered')
plt4.set_title('TcpScalable')
plt4.set_xlabel('Time(Seconds)')
plt4.set_ylabel('Cumulative byte Transfered')
plt5.set_title('TcpVegas')
plt5.set_xlabel('Time(Seconds)')
plt5.set_ylabel('Cumulative byte Transfered')

plt1.grid()
plt2.grid()
plt3.grid()
plt4.grid()
plt5.grid()

fig.subplots_adjust(hspace=.5,wspace=0.5) 
fig.show()